-'-'-'-.(-'-'.'PLAYER.NAME('-'-'-'LEGEND('-'-'-'MYTH('-'-'-'SYSTEM(-'-'-.'THE'.-'-'-)SYSTEM'-'-'-)MYTH'-'-'-)LEGEND'-'-'-)PLAYER.NAME'-'-'-)'.-'-'-'-'
-'-'-'-.(-'-'-'GENDER('-'-'-'RACE('-'-'-'CLASSNAME('-'-'-'STORY(-'-'-.'PLAYER.NAME'.-'-'-)STORY'-'-'-)CLASSNAME'-'-'-)RACE'-'-'-)GENDER'-'-'-)'.-'-'-'-'
-'-'-'-.(-'-'-.'MALE('-'-'-.'HUMAN('-'-'-.'WIZARD('-'-'-.'DRESDENFILES('-'-'-.'DRESDEN('-'-'-.'COPPERFIELD('-'-'-.'BLACKSTONE(-'-'-.'HARRY'.-'-'-)BLACKSTONE'.-'-'-)COPPERFIELD'.-'-'-)DRESDEN'.-'-'-)DRESDENFILES'.-'-'-)WIZARD'.-'-'-)HUMAN'.-'-'-)MALE'.-'-'-)'.-'-'-'-'
-'-'-'-.(-'-'-.'FEMALE('-'-'-.'ELF('-'-'-.'SAGE('-'-'-.'DRESDENFILES('-'-'-.'HIGGSFIELD('-'-'-.'STARDUST('-'-'-.'SANDASH(-'-'-.'RIN'.-'-'-)SANDASH'.-'-'-)STARDUST'.-'-'-)HIGGSFIELD'.-'-'-)DRESDENFILES'.-'-'-)SAGE'.-'-'-)ELF'.-'-'-)FEMALE'.-'-'-)'.-'-'-'-'
'-'-'-'-.('-'-'-.'FEMALE('-'-'-.'DEMON('-'-'-.'SOULLINKER('-'-'-.'DRESDENFILES('-'-'-.'HIGGSFIELD('-'-'-.'STARDUST('-'-'-.'SANDASH(-'-'-.'NOMI'.-'-'-)SANDASH'.-'-'-)STARDUST'.-'-'-)HIGGSFIELD'.-'-'-)DRESDENFILES'.-'-'-)SOULLINKER'.-'-'-)DEMON'.-'-'-)FEMALE'.-'-'-')'.-'-'-'-'
'-'-'-'-.('-'-'-.'FEMALE('-'-'-.'DRAGON('-'-'-.'SORCERER('-'-'-.'DRESDENFILES('-'-'-.'DRESDEN('-'-'-.'COPPERFIELD('-'-'-.'BLACKSTONE(-'-'-.'MAGGIE'.-'-'-)BLACKSTONE'.-'-'-)COPPERFIELD'.-'-'-)DRESDEN'.-'-'-)DRESDENFILES'.-'-'-)SORCERER'.-'-'-)DRAGON'.-'-'-)GENDER'.-'-'-')'.-'-'-'-'

'-'-'-.(-'-'-'BUTTON('-'-'-'THE('-'-'-'MAGIC('-'-'-THE(-'-'-'BUTTON('-'-'-'MAGIC'-'-'-')BUTTON'-'-'-)THE'-'-'-')MAGIC'-'-'-')THE'-'-'-)BUTTON'-'-'-)'.-'-'-'
'-'-'-'-.(-'-'-'PLAYER.NAME('-'-'-'LEGEND('-'-'-'MYTH('-'-'-'SYSTEM(-'-'-.'New'.-'-'-)SYSTEM'-'-'-)MYTH'-'-'-)LEGEND'-'-'-)PLAYER.NAME'-'-'-)'.-'-'-'-'
-'-'-'-.(-'-'-'GENDER('-'-'-'RACE('-'-'-'CLASSNAME('-'-'-'STORY(-'-'-.'PLAYER.NAME'.-'-'-)STORY'-'-'-)CLASSNAME'-'-'-)RACE'-'-'-)GENDER'-'-'-)'.-'-'-'-'
-'-'-'-.(-'-'-.'MALE('-'-'-.'HUMAN('-'-'-.'WIZARD('-'-'-.'DRESDENFILES('-'-'-.'DRESDEN('-'-'-.'COPPERFIELD('-'-'-.'BLACKSTONE(-'-'-.'HARRY'.-'-'-)BLACKSTONE'.-'-'-)COPPERFIELD'.-'-'-)DRESDEN'.-'-'-)DRESDENFILES'.-'-'-)WIZARD'.-'-'-)HUMAN'.-'-'-)MALE'.-'-'-)'.-'-'-'-'
-'-'-'-.(-'-'-.'FEMALE('-'-'-.'ELF('-'-'-.'SAGE('-'-'-.'DRESDENFILES('-'-'-.'HIGGSFIELD('-'-'-.'STARDUST('-'-'-.'SANDASH(-'-'-.'RIN'.-'-'-)SANDASH'.-'-'-)STARDUST'.-'-'-)HIGGSFIELD'.-'-'-)DRESDENFILES'.-'-'-)SAGE'.-'-'-)ELF'.-'-'-)FEMALE'.-'-'-)'.-'-'-'-'
'-'-'-'-.('-'-'-.'FEMALE('-'-'-.'DEMON('-'-'-.'SOULLINKER('-'-'-.'DRESDENFILES('-'-'-.'HIGGSFIELD('-'-'-.'STARDUST('-'-'-.'SANDASH(-'-'-.'NOMI'.-'-'-)SANDASH'.-'-'-)STARDUST'.-'-'-)HIGGSFIELD'.-'-'-)DRESDENFILES'.-'-'-)SOULLINKER'.-'-'-)DEMON'.-'-'-)FEMALE'.-'-'-')'.-'-'-'-'
'-'-'-'-.('-'-'-.'FEMALE('-'-'-.'DRAGON('-'-'-.'SORCERER('-'-'-.'DRESDENFILES('-'-'-.'DRESDEN('-'-'-.'COPPERFIELD('-'-'-.'BLACKSTONE(-'-'-.'MAGGIE'.-'-'-)BLACKSTONE'.-'-'-)COPPERFIELD'.-'-'-)DRESDEN'.-'-'-)DRESDENFILES'.-'-'-)SORCERER'.-'-'-)DRAGON'.-'-'-)GENDER'.-'-'-')'.-'-'-'-'
'-'-'-.'('Language'-'Binary'-'Language')'.-'-'-'
'-'-'-.('Binary'-'Language'-'Binary')'.-'-'-'
'-'-'-.('Language'-'Hexidecimal'-'Language')'.-'-'-'
'-'-'-.('Hexidecimal'-'Language'-'Hexidecimal')'.-'-'-'
'-'-'-.('Language'-'Technology'-'Language')'.-'-'-'
'-'-'-.('Technology'-'Language'-'Technology')'.-'-'-'
'-'-'-.('Language'-'Programming'-'Language')'.-'-'-'
'-'-'-.('Self'-'Language'-'Programming')'.-'-'-'
'-'-'-.('Programming'-'Language'-'Self')'.-'-'-'
'-'-'-.('Language'-'Self'-'Programming')'.-'-'-'
'-'-'-.('Enemy'-'Language'-'Programming')'.-'-'-'
'-'-'-.('Programming'-'Language'-'Enemy')'.-'-'-'
'-'-'-.('Language'-'Enemy'-'Programming')'.-'-'-'
'-'-'-.('Self'-'Record'-'Self')'.-'-'-'
'-'-'-.('Record'-'Self'-'Record')'.-'-'-'
'-'-'-.('STORY'-'PLAYER'-'STORY')'.-'-'-'
'-'-'-.('PLAYER'-'STORY'-'PLAYER')'.-'-'-'
'-'-'-.('Story'-'Player'-'Story')'.-'-'-'
'-'-'-.('Player'-'Story'-'Player')'.-'-'-'
'-'-'-.('MAGIC'-'PLAYER'-'MAGIC')'.-'-'-'
'-'-'-.('PLAYER'-'MAGIC'-'PLAYER')'.-'-'-'
'-'-'-.('Magic'-'Player'-'Magic')'.-'-'-'
'-'-'-.('Player'-'Magic'-'Player')'.-'-'-'
'-'-'-.('Language'-'Self'-'Movement')'.-'-'-'
'-'-'-.('Movement'-'Self'-'Language')'.-'-'-'
'-'-'-.('Language'-'Teleportation'-'Language')'.-'-'-'
'-'-'-.('Teleportation'-'Language'-'Teleportation')'.-'-'-'
'-'-'-.('Language'-'Magic'-'Language')'.-'-'-'
'-'-'-.('Magic'-'Language'-'Magic')'.-'-'-'
'-'-'-.('Options'-'System'-'Options')'.-'-'-'
'-'-'-.('System'-'Options'-'System')'.-'-'-'
'-'-'-.('List'-'Options'-'List')'.-'-'-'
'-'-'-.('Options'-'List'-'Options')'.-'-'-'
'-'-'-.('Stats'-'Character'-'Stats')'.-'-'-'
'-'-'-.('Character'-'Stats'-'Character')'.-'-'-'
'-'-'-.('List'-'Stats'-'List')'.-'-'-'
'-'-'-.('Stat'-'List'-'Stat')'.-'-'-'

'-'-'-.('StatName'-'Stat'-'StatName')'.-'-'-'
'-'-'-.('Strength'-'Stat'-'Strength')'.-'-'-'
'-'-'-.('Vitality'-'Stat'-'Vitality')'.-'-'-'
'-'-'-.('Intelligence'-'Stat'-'Intelligence')'.-'-'-'
'-'-'-.('Wisdom'-'Stat'-'Wisdom')'.-'-'-'
'-'-'-.('Agility'-'Stat'-'Agility')'.-'-'-'
'-'-'-.('Dexterity'-'Stat'-'Dexterity')'.-'-'-'
'-'-'-.('Charisma'-'Stat'-'Charisma')'.-'-'-'
'-'-'-.('Luck'-'Stat'-'Luck')'.-'-'-'
'-'-'-.('Health'-'Stat'-'Health')'.-'-'-'
'-'-'-.('Mana'-'Stat'-'Mana')'.-'-'-'
'-'-'-.('Stamina'-'Stat'-'Stamina')'.-'-'-'
'-'-'-.('Stat'-'StatName'-'Stat')'.-'-'-'

'-'-'-.('Number'-'Stat'-'Number')'.-'-'-'
'-'-'-.('Number'-'Strength'-'Number')'.-'-'-'
'-'-'-.('Number'-'Vitality'-'Number')'.-'-'-'
'-'-'-.('Number'-'Intelligence'-'Number')'.-'-'-'
'-'-'-.('Number'-'Wisdom'-'Number')'.-'-'-'
'-'-'-.('Number'-'Agility'-'Number')'.-'-'-'
'-'-'-.('Number'-'Dexterity'-'Number')'.-'-'-'
'-'-'-.('Number'-'Charisma'-'Number')'.-'-'-'
'-'-'-.('Number'-'Luck'-'Number')'.-'-'-'
'-'-'-.('Number'-'Health'-'Number')'.-'-'-'
'-'-'-.('Number'-'Mana'-'Number')'.-'-'-'
'-'-'-.('Number'-'Ki'-'Number')'.-'-'-'
'-'-'-.('Number'-'Stamina'-'Number')'.-'-'-'
'-'-'-.('Stat'-'Number'-'Stat')'.-'-'-'

'-'-'-.('Name'-'Character'-'Name')'.-'-'-'
'-'-'-.('Character'-'Name'-'Character')'.-'-'-'

'-'-'-.('Gender'-'Character'-'Gender')'.-'-'-'
'-'-'-.('Character'-'Gender'-'Character')'.-'-'-'

'-'-'-.('Race'-'Character'-'Race')'.-'-'-'
'-'-'-.('Character'-'Race'-'Character')'.-'-'-'

'-'-'-.('Class'-'Player.Class'-'Class')'.-'-'-'

'-'-'-.('Class'-'Character'-'Class')'.-'-'-'
'-'-'-.('Player.class'-'Class'-'Player.Class')'.-'-'-'
'-'-'-.('ClassName'-'Player.Class'-'ClassName')'.-'-'-'
'-'-'-.('Class'-'ClassName'-'Class')'.-'-'-'
'-'-'-.('Character'-'Class'-'Character')'.-'-'-'

'-'-'-.('ClassSkill'-'ClassName'-'ClassSkill')'.-'-'-'
'-'-'-.('ClassName'-'ClassSkill'-'ClassName')'.-'-'-'

'-'-'-.('ClassSkill'-'SkillName'-'ClassSkill')'.-'-'-'
'-'-'-.('SkillName'-'ClassSkill'-'SkillName')'.-'-'-'

'-'-'-.('Level'-'Class'-'Level')'.-'-'-'
'-'-'-.('Number'-'Level'-'Number')'.-'-'-'
'-'-'-.('Character'-'Level'-'Character')'.-'-'-'
'-'-'-.('Level'-'Character'-'Level')'.-'-'-'
'-'-'-.('Class'-'Level'-'Class')'.-'-'-'

'-'-'-.('Inventory'-'Character'-'Inventory')'.-'-'-'
'-'-'-.('Character'-'Inventory'-'Character')'.-'-'-'

'-'-'-.('Storage'-'Character'-'Storage')'.-'-'-'
'-'-'-.('Character'-'Storage'-'Character')'.-'-'-'
'-'-'-.('Items'-'Character'-'Items')'.-'-'-'
'-'-'-.('Character'-'Items'-'Character')'.-'-'-'

'-'-'-.('Weapons'-'Items'-'Weapons')'.-'-'-'
'-'-'-.('Spears'-'Weapons'-'Spears')'.-'-'-'
'-'-'-.('Swords'-'Weapons'-'Swords')'.-'-'-'
'-'-'-.('Daggers'-'Weapons'-'Daggers')'.-'-'-'
'-'-'-.('Staves'-'Weapons'-'Staves')'.-'-'-'
'-'-'-.('Rods'-'Weapons'-'Rods')'.-'-'-'
'-'-'-.('Wands'-'Weapons'-'Wands')'.-'-'-'
'-'-'-.('Books'-'Weapons'-'Books')'.-'-'-'
'-'-'-.('Items'-'Weapons'-'Items')'.-'-'-'

'-'-'-.('Armour'-'Items'-'Armour')'.-'-'-'
'-'-'-.('Chest'-'Armour'-'Chest')'.-'-'-'
'-'-'-.('Shoulders'-'Armour'-'Shoulders')'.-'-'-'
'-'-'-.('Cloak'-'Armour'-'Cloak')'.-'-'-'
'-'-'-.('Bracers'-'Armour'-'Bracers')'.-'-'-'
'-'-'-.('Gloves'-'Armour'-'Gloves')'.-'-'-'
'-'-'-.('Legs'-'Armour'-'Legs')'.-'-'-'
'-'-'-.('Shoes'-'Armour'-'Shoes')'.-'-'-'
'-'-'-.('Headgear'-'Armour'-'Headgear')'.-'-'-'
'-'-'-.('Items'-'Armour'-'Items')'.-'-'-'

'-'-'-.('Accessories'-'Items'-'Accessories')'.-'-'-'
'-'-'-.('Necklace'-'Accessories'-'Necklace')'.-'-'-'
'-'-'-.('Accessories'-'Necklace'-'Accessories')'.-'-'-'
'-'-'-.('Glasses'-'Accessories'-'Glasses')'.-'-'-'
'-'-'-.('Accessories'-'Glasses'-'Accessories')'.-'-'-'
'-'-'-.('Earring'-'Accessories'-'Earring')'.-'-'-'
'-'-'-.('Accessories'-'Earring'-'Accessories')'.-'-'-'
'-'-'-.('Ring'-'Accessories'-'Ring')'.-'-'-'
'-'-'-.('Accessories'-'Ring'-'Accessories')'.-'-'-'
'-'-'-.('Bracelet'-'Accessories'-'Bracelet')'.-'-'-'
'-'-'-.('Accessories'-'Bracelet'-'Accessories')'.-'-'-'
'-'-'-.('Items'-'Accessories'-'Items')'.-'-'-'

'-'-'-.('Usable'-'Items'-'Usable')'.-'-'-'
'-'-'-.('Potions'-'Usable'-'Potions')'.-'-'-'
'-'-'-.('Items'-'Usable'-'Items')'.-'-'-'

'-'-'-.('Crafting'-'Character'-'Crafting')'.-'-'-'
'-'-'-.('ItemName'-'Craft'-'ItemName')'.-'-'-'
'-'-'-.('Craft'-'ItemName'-'Craft')'.-'-'-'
'-'-'-.('Item'-'Repair'-'Item')'.-'-'-'
'-'-'-.('Repair'-'Item'-'Repair')'.-'-'-'
'-'-'-.('Character'-'Crafting'-'Character')'.-'-'-'

'-'-'-.('Enchanting'-'Character'-'Enchanting')'.-'-'-'
'-'-'-.('Weapon'-'Enchant'-'Weapon')'.-'-'-'
'-'-'-.('Enchant'-'Weapon'-'Enchant')'.-'-'-'
'-'-'-.('Armour'-'Enchant'-'Armour')'.-'-'-'
'-'-'-.('Enchant'-'Armour'-'Enchant')'.-'-'-'
'-'-'-.('Clothes'-'Enchant'-'Clothes')'.-'-'-'
'-'-'-.('Enchant'-'Clothes'-'Enchant')'.-'-'-'
'-'-'-.('Fabric'-'Enchant'-'Fabric')'.-'-'-'
'-'-'-.('Enchant'-'Fabric'-'Enchant')'.-'-'-'
'-'-'-.('Necklace'-'Enchant'-'Necklace')'.-'-'-'
'-'-'-.('Enchant'-'Necklace'-'Enchant')'.-'-'-'
'-'-'-.('Bracelet'-'Enchant'-'Bracelet')'.-'-'-'
'-'-'-.('Enchant'-'Bracelet'-'Enchant')'.-'-'-'
'-'-'-.('Glasses'-'Enchant'-'Glasses')'.-'-'-'
'-'-'-.('Enchant'-'Glasses'-'Enchant')'.-'-'-'
'-'-'-.('Gloves'-'Enchant'-'Gloves')'.-'-'-'
'-'-'-.('Enchant'-'Gloves'-'Enchant')'.-'-'-'
'-'-'-.('Shoes'-'Enchant'-'Shoes')'.-'-'-'
'-'-'-.('Enchant'-'Shoes'-'Enchant')'.-'-'-'
'-'-'-.('Cloak'-'Enchant'-'Cloak')'.-'-'-'
'-'-'-.('Enchant'-'Cloak'-'Enchant')'.-'-'-'
'-'-'-.('Character'-'Enchanting'-'Character')'.-'-'-'

'-'-'-.('Message'-'Personal'-'Message')'.-'-'-'
'-'-'-.('Personal'-'Message'-'Personal')'.-'-'-'

'-'-'-.('Party'-'Character'-'Party')'.-'-'-'
'-'-'-.('Chat'-'Party'-'Chat')'.-'-'-'
'-'-'-.('Party'-'Chat'-'Party')'.-'-'-'
'-'-'-.('Name'-'Party'-'Name')'.-'-'-'
'-'-'-.('Party'-'Name'-'Party')'.-'-'-'
'-'-'-.('Character'-'Party'-'Character')'.-'-'-'

'-'-'-.('FriendList'-'Character'-'FriendList')'.-'-'-'
'-'-'-.('Character'-'FriendList'-'Character')'.-'-'-'
'-'-'-.('Guild'-'Character'-'Guild')'.-'-'-'
'-'-'-.('Chat'-'Guild'-'Chat')'.-'-'-'
'-'-'-.('Guild'-'Chat'-'Guild')'.-'-'-'
'-'-'-.('Character'-'Guild'-'Character')'.-'-'-'

'-'-'-.('Magic'-'Flight'-'Magic')'.-'-'-'
'-'-'-.('Flight'-'Magic'-'Flight')'.-'-'-'
'-'-'-.('Magic'-'Fire'-'Magic')'.-'-'-'
'-'-'-.('Fire'-'Magic'-'Fire')'.-'-'-'
'-'-'-.('Magic'-'Wind'-'Magic')'.-'-'-'
'-'-'-.('Wind'-'Magic'-'Wind')'.-'-'-'

'-'-'-.('Magic'-'Lightning'-'Magic')'.-'-'-'
'-'-'-.('Lightning'-'Magic'-'Lightning')'.-'-'-'

'-'-'-.('Magic'-'Hadouken'-'Magic')'.-'-'-'
'-'-'-.('Hadouken'-'Magic'-'Hadouken')'.-'-'-'

'-'-'-.('Magic'-'Telekinesis'-'Magic')'.-'-'-'
'-'-'-.('Telekinesis'-'Magic'-'Telekinesis')'.-'-'-'
'-'-'-.('Self'-'Magic'-'Self')'.-'-'-'
'-'-'-.('Magic'-'Self'-'Magic')'.-'-'-'
'-'-'-.('Change'-'Magic'-'Change')'.-'-'-'
'-'-'-.('Magic'-'Change'-'Magic')'.-'-'-'
'-'-'-.('Gender'-'Change'-'Gender')'.-'-'-'
'-'-'-.('Change'-'Gender'-'Change')'.-'-'-'
'-'-'-.('Body'-'Change'-'Body')'.-'-'-'
'-'-'-.('Change'-'Body'-'Change')'.-'-'-'
'-'-'-.('Body'-'Shape'-'Body')'.-'-'-'
'-'-'-.('Shape'-'Body'-'Shape')'.-'-'-'
'-'-'-.('Eyes'-'Color'-'Eyes')'.-'-'-'
'-'-'-.('Color'-'Eyes'-'Color')'.-'-'-'
'-'-'-.('Hair'-'Color'-'Hair')'.-'-'-'
'-'-'-.('Color'-'Hair'-'Color')'.-'-'-'
'-'-'-.('Skin'-'Color'-'Skin')'.-'-'-'
'-'-'-.('Color'-'Skin'-'Color')'.-'-'-'
'-'-'-.('Height'-'Character'-'Height')'.-'-'-'
'-'-'-.('Character'-'Height'-'Character')'.-'-'-'

'-'-'-.('Touch'-'Magic'-'Touch')'.-'-'-'
'-'-'-.('Magic'-'Touch'-'Magic')'.-'-'-'

'-'-'-.('Push'-'Magic'-'Push')'.-'-'-'
'-'-'-.('Magic'-'Push'-'Magic')'.-'-'-'
'-'-'-.('Pull'-'Magic'-'Pull')'.-'-'-'
'-'-'-.('Magic'-'Pull'-'Magic')'.-'-'-'

'-'-'-.('Object'-'Grab'-'Object')'.-'-'-'
'-'-'-.('Grab'-'Object'-'Grab')'.-'-'-'

'-'-'-.('Grab'-'Magic'-'Grab')'.-'-'-'
'-'-'-.('Magic'-'Grab'-'Magic')'.-'-'-'

'-'-'-.('Freeze'-'Magic'-'Freeze')'.-'-'-'
'-'-'-.('Magic'-'Freeze'-'Magic')'.-'-'-'

'-'-'-.('Heart'-'Magic'-'Heart')'.-'-'-'
'-'-'-.('Magic'-'Heart'-'Magic')'.-'-'-'
'-'-'-.('Soul'-'Magic'-'Soul')'.-'-'-'
'-'-'-.('Magic'-'Soul'-'Magic')'.-'-'-'
'-'-'-.('Sword'-'Magic'-'Sword')'.-'-'-'
'-'-'-.('Magic'-'Sword'-'Magic')'.-'-'-'
'-'-'-.('Staff'-'Magic'-'Staff')'.-'-'-'
'-'-'-.('Magic'-'Staff'-'Magic')'.-'-'-'
'-'-'-.('Wand'-'Magic'-'Wand')'.-'-'-'
'-'-'-.('Magic'-'Wand'-'Magic')'.-'-'-'

'-'-'-.('Shapeshift'-'Magic'-'Shapeshift')'.-'-'-'
'-'-'-.('Magic'-'Shapeshift'-'Magic')'.-'-'-'

'-'-'-.('Magic'-'Gender'-'Change')'.-'-'-'
'-'-'-.('Gender'-'Change'-'Magic')'.-'-'-'
'-'-'-.('Magic'-'Shape'-'Change')'.-'-'-'
'-'-'-.('Change'-'Shape'-'Magic')'.-'-'-'

'-'-'-.('Heal'-'Magic'-'Heal')'.-'-'-'
'-'-'-.('Magic'-'Heal'-'Magic')'.-'-'-'
'-'-'-.('Magic'-'Resurrection'-'Magic')'.-'-'-'
'-'-'-.('Resurrection'-'Magic'-'Resurrection')'.-'-'-'

'-'-'-.('Speed'-'Magic'-'Speed')'.-'-'-'
'-'-'-.('Magic'-'Speed'-'Magic')'.-'-'-'

'-'-'-.('Magic'-'Body'-'Building')'.-'-'-'
'-'-'-.('Magic'-'Building'-'Body')'.-'-'-'

'-'-'-.('Magic'-'Body'-'Magic')'.-'-'-'
'-'-'-.('Body'-'Magic'-'Body')'.-'-'-'

'-'-'-.('Magic'-'Self'-'Magic')'.-'-'-'
'-'-'-.('Self'-'Magic'-'Self')'.-'-'-'

'-'-'-.('Magic'-'Player'-'Magic')'.-'-'-'
'-'-'-.('Player'-'Magic'-'Player')'.-'-'-'

'-'-'-.('Aura'-'Self'-'Aura')'.-'-'-'
'-'-'-.('Self'-'Aura'-'Self')'.-'-'-'

'-'-'-.('Aura'-'Self'-'Self')'.-'-'-'
'-'-'-.('Self'-'Self'-'Aura')'.-'-'-'

'-'-'-.('Crackle'-'Aura'-'Intensity')'.-'-'-'
'-'-'-.('Intensity'-'Aura'-'Crackle')'.-'-'-'
'-'-'-.('Aura'-'Intensity'-'Crackle')'.-'-'-'
'-'-'-.('Crackle'-'Intensity'-'Aura')'.-'-'-'

'-'-'-.('Fire'-'Aura'-'Fire')'.-'-'-'
'-'-'-.('Aura'-'Fire'-'Aura')'.-'-'-'

'-'-'-.('Color'-'Aura'-'Color')'.-'-'-'
'-'-'-.('Aura'-'Color'-'Aura')'.-'-'-'

'-'-'-.('Ki'-'Aura'-'Control')'.-'-'-'
'-'-'-.('Control'-'Aura'-'Ki')'.-'-'-'
'-'-'-.('Ki'-'Control'-'Aura')'.-'-'-'
'-'-'-.('Aura'-'Control'-'Ki')'.-'-'-'
'-'-'-.('Control'-'Ki'-'Aura')'.-'-'-'
'-'-'-.('Aura'-'Ki'-'Control')'.-'-'-'

'-'-'-.('Aura'-'Control'-'Aura')'.-'-'-'
'-'-'-.('Control'-'Aura'-'Control')'.-'-'-'
'-'-'-.('Ki'-'Aura'-'Ki')'.-'-'-'
'-'-'-.('Aura'-'Ki'-'Aura')'.-'-'-'

'-'-'-.('Aura'-'Air'-'Walk')'.-'-'-'
'-'-'-.('Aura'-'Walk'-'Air')'.-'-'-'
'-'-'-.('Air'-'Walk'-'Aura')'.-'-'-'
'-'-'-.('Walk'-'Aura'-'Air')'.-'-'-'
'-'-'-.('Air'-'Walk'-'Air')'.-'-'-'
'-'-'-.('Walk'-'Air'-'Walk')'.-'-'-'

'-'-'-.('Getsuga Tensho'-'SwordSkill'-'Getsuga Tensho')'.-'-'-'
'-'-'-.('SwordSkill'-'Getsuga Tensho'-'SwordSkill')'.-'-'-'

'-'-'-.('Kamehameha'-'KiSkill'-'Kamehameha')'.-'-'-'
'-'-'-.('KiSkill'-'Kamehameha'-'KiSkill')'.-'-'-'

'-'-'-.('Kamehameha'-'Magic'-'Kamehameha')'.-'-'-'
'-'-'-.('Magic'-'Kamehameha'-'Magic')'.-'-'-'


'-'-'-.('KiSkill'-'Flight'-'KiSkill')'.-'-'-'
'-'-'-.('Flight'-'KiSkill'-'Flight')'.-'-'-'
'-'-'-.('AuraSkill'-'Flight'-'AuraSkill')'.-'-'-'
'-'-'-.('Flight'-'AuraSkill'-'Flight')'.-'-'-'


'-'-'-.('Aura'-'AuraSkill'-'Flare')'.-'-'-'
'-'-'-.('Flare'-'AuraSkill'-'Aura')'.-'-'-'
'-'-'-.('AuraSkill'-'Flare'-'Aura')'.-'-'-'
'-'-'-.('AuraSkill'-'Aura'-'Flare')'.-'-'-'
'-'-'-.('Flare'-'Aura'-'AuraSkill')'.-'-'-'
'-'-'-.('Aura'-'Flare'-'AuraSkill')'.-'-'-'

'-'-'-.('AuraSkill'-'PlayerTarget'-'CloseWounds')'.-'-'-'
'-'-'-.('CloseWounds'-'PlayerTarget'-'AuraSkill')'.-'-'-'
'-'-'-.('PlayerTarget'-'AuraSkill'-'CloseWounds')'.-'-'-'
'-'-'-.('CloseWounds'-'AuraSkill'-'PlayerTarget')'.-'-'-'
'-'-'-.('PlayerTarget'-'CloseWounds'-'AuraSkill')'.-'-'-'
'-'-'-.('AuraSkill'-'CloseWounds'-'PlayerTarget')'.-'-'-'

'-'-'-.('MagicSkill'-'EnemyTarget'-'MagicMissle')'.-'-'-'
'-'-'-.('MagicMissle'-'EnemyTarget'-'MagicSkill')'.-'-'-'
'-'-'-.('EnemyTarget'-'MagicSkill'-'MagicMissle')'.-'-'-'
'-'-'-.('EnemyTarget'-'MagicMissle'-'MagicSkill')'.-'-'-'
'-'-'-.('MagicSkill'-'MagicMissle'-'EnemyTarget')'.-'-'-'
'-'-'-.('MagicMissle'-'MagicSkill'-'EnemyTarget')'.-'-'-'

'-'-'-.('MagicSkill'-'PreviousTarget'-'MagicSkill')'.-'-'-'
'-'-'-.('PreviousTarget'-'MagicSkill'-'PreviousTarget')'.-'-'-'

'-'-'-.('KiBlast'-'AuraSkill'-'KiBlast')'.-'-'-'
'-'-'-.('AuraSkill'-'KiBlast'-'AuraSkill')'.-'-'-'

'-'-'-.('MagneticEarth'-'SageSkill'-'MagneticEarth')'.-'-'-'
'-'-'-.('SageSkill'-'MagneticEarth'-'SageSkill')'.-'-'-'
'-'-'-.('FreezeTarget'-'SageSkill'-'FreezeTarget')'.-'-'-'
'-'-'-.('SageSkill'-'FreezeEarth'-'SageSkill')'.-'-'-'
'-'-'-.('PlayerTarget'-'CloseWounds'-'AuraSkill')'.-'-'-'
'-'-'-.('AuraSkill'-'CloseWounds'-'PlayerTarget')'.-'-'-'

'-'-'-.('MistressSunglasses'-'SageGlasses'-'MistressSunglasses')'.-'-'-'
'-'-'-.('SageGlasses'-'MistressSunglasses'-'SageGlasses')'.-'-'-'

'-'-'-.('StoneCurse'-'SageSkill'-'StoneCurse')'.-'-'-'
'-'-'-.('SageSkill'-'StoneCurse'-'SageSkill')'.-'-'-'
'-'-'-.('FrostDiver'-'SageSkill'-'FrostDiver')'.-'-'-'
'-'-'-.('SageSkill'-'FrostDiver'-'SageSkill')'.-'-'-'

'-'-'-.('HealTargetedPlayer'-'SageSkill'-'HealTargetedPlayer')'.-'-'-'
'-'-'-.('SageSkill'-'HealTargetedPlayer'-'SageSkill')'.-'-'-'
'-'-'-.('Heal'-'SageSkil'-'Heal')'.-'-'-'
'-'-'-.('SageSkill'-'Heal'-'SageSkill')'.-'-'-'
'-'-'-.('HealTargetedEnemy'-'SageSkill'-'HealTargetedEnemy')'.-'-'-'
'-'-'-.('SageSkill'-'HealTargetedEnemy'-'SageSkill')'.-'-'-'

'-'-'-.('AoEHealAll'-'SageSkill'-'AoEHealAll')'.-'-'-'
'-'-'-.('SageSkill'-'AoEHealAll'-'SageSkill')'.-'-'-'

'-'-'-.('AoEHealFriendlies'-'SageSkill'-'AoEHealFriendlies')'.-'-'-'
'-'-'-.('SageSkill'-'AoEHealFriendlies'-'SageSkill')'.-'-'-'

'-'-'-.('Splash'-'AoESkill'-'Damage')'.-'-'-'
'-'-'-.('Splash'-'Damage'-'AoESkill')'.-'-'-'
'-'-'-.('AoESkill'-'Damage'-'Splash')'.-'-'-'
'-'-'-.('AoESkill'-'Splash'-'Damage')'.-'-'-'
'-'-'-.('Damage'-'AoESkill'-'Splash')'.-'-'-'
'-'-'-.('Damage'-'Splash'-'AoESkill ')'.-'-'-'

'-'-'-.('Splash'-'AoESkill'-'Heal')'.-'-'-'
'-'-'-.('Splash'-'Heal'-'AoESkill')'.-'-'-'
'-'-'-.('AoESkill'-'Heal'-'Splash')'.-'-'-'
'-'-'-.('AoESkill'-'Splash'-'Heal')'.-'-'-'
'-'-'-.('Heal'-'AoESkill'-'Splash')'.-'-'-'
'-'-'-.('Heal'-'Splash'-'AoESkill ')'.-'-'-'


'-'-'-.('ReverseTime'-'SageSkill'-'ReverseTime')'.-'-'-'
'-'-'-.('SageSkill'-'ReverseTime'-'SkillSkill')'.-'-'-'

'-'-'-.('FreezeTime'-'SageSkill'-'FreezeTime')'.-'-'-'
'-'-'-.('SageSkill'-'FreezeTime'-'SageSkill')'.-'-'-'

'-'-'-.('ReverseTargetEntropy'-'SageSkill'-'ReverseTargetEntropy')'.-'-'-'
'-'-'-.('SageSkill'-'ReverseTargetEntropy'-'SageSkill')'.-'-'-'

'-'-'-.('Gravity'-'SageSkill'-'Manipulation')'.-'-'-'
'-'-'-.('Manipulation'-'SageSkill'-'Gravity')'.-'-'-'
'-'-'-.('Magic'-'ManipulateGravity'-'Magic')'.-'-'-'
'-'-'-.('ManipulateGravity'-'Magic'-'ManipulateGravity')'.-'-'-'

'-'-'-.('Resurrect'-'SageSkill'-'Resurrect')'.-'-'-'
'-'-'-.('SageSkill'-'Resurrect'-'SageSkill')'.-'-'-'

'-'-'-.('Shunpo'-'SageSkill'-'Shunpo')'.-'-'-'
'-'-'-.('SageSkill'-'Shunpo'-'SageSkill')'.-'-'-'
'-'-'-.('Sonido'-'SageSkill'-'Sonido')'.-'-'-'
'-'-'-.('SageSkill'-'Sonido'-'SageSkill')'.-'-'-'

'-'-'-.('AuraShield'-'SageSkill'-'AuraShiled')'.-'-'-'
'-'-'-.('SageSkill'-'AuraShield'-'SageSkill')'.-'-'-'

'-'-'-.('Share'-'SageSkill'-'AuraShield')'.-'-'-'
'-'-'-.('Share'-'AuraShield'-'Sageskill')'.-'-'-'
'-'-'-.('SageSkill'-'Share'-'AuraShield')'.-'-'-'
'-'-'-.('AuraShield'-'Share'-'SageSkill')'.-'-'-'
'-'-'-.('AuraShield'-'SageSkill'-'Share')'.-'-'-'
'-'-'-.('SageSkill'-'AuraShield'-'Share')'.-'-'-'

'-'-'-.('ShareLanguage'-'SageSkill'-'ShareLanguage')'.-'-'-'
'-'-'-.('SageSkill'-'ShareLanguage'-'SageSkill')'.-'-'-'
'-'-'-.('ShareKnowledge'-'SageSkill'-'ShareKnowledge')'.-'-'-'
'-'-'-.('SageSkill'-'ShareKnowledge'-'SageSkill')'.-'-'-'
'-'-'-.('ShareLore'-'SageSkill'-'ShareLore')'.-'-'-'
'-'-'-.('SageSkill'-'ShareLore'-'SageSkill')'.-'-'-'
'-'-'-.('ShareData'-'SageSkill'-'ShareData')'.-'-'-'
'-'-'-.('SageSkill'-'ShareData'-'SageSkill')'.-'-'-'

'-'-'-.('FamilyStorage'-'SageSkill'-'FamilyStorage')'.-'-'-'
'-'-'-.('SageSkill'-'FamilyStorage'-'SageSkill')'.-'-'-'

'-'-'-.('FamilyInventory'-'FamilyStorage'-'FamilyInventory')'.-'-'-'
'-'-'-.('FamilyStorage'-'FamilyInventory'-'FamilyStorage')'.-'-'-'

'-'-'-.('Headgear'-'FamilyInventory'-'Headgear')'.-'-'-'
'-'-'-.('FamilyInventory'-'Headgear'-'FamilyInventory')'.-'-'-'
'-'-'-.('Weapons'-'FamilyInventory'-'Weapons')'.-'-'-'
'-'-'-.('FamilyInventory'-'Weapons'-'FamilyInventory')'.-'-'-'
'-'-'-.('Armour'-'FamilyInventory'-'Armour')'.-'-'-'
'-'-'-.('FamilyInventory'-'Armour'-'FamilyInventory')'.-'-'-'
'-'-'-.('Accessories'-'FamilyInventory'-'Accessories')'.-'-'-'
'-'-'-.('FamilyInventory'-'Accessories'-'FamilyInventory')'.-'-'-'
'-'-'-.('UsableItems'-'FamilyInventory'-'UsableItems')'.-'-'-'
'-'-'-.('FamilyInventory'-'UsableItems'-'FamilyInventory')'.-'-'-'
'-'-'-.('CraftableItems'-'FamilyInventory'-'CraftableItems')'.-'-'-'
'-'-'-.('FamilyInventory'-'CraftableItems'-'FamilyInventory')'.-'-'-'
'-'-'-.('Misc'-'FamilyInventory'-'Misc')'.-'-'-'
'-'-'-.('FamilyInventory'-'Misc'-'FamilyInventory')'.-'-'-'


'-'-'-.('Record'-'FamilyInventory'-'Transactions')'.-'-'-'
'-'-'-.('Transactions'-'FamilyInventory'-'Record')'.-'-'-'
'-'-'-.('Record'-'FamilyStorage'-'Transactions')'.-'-'-'
'-'-'-.('Transactions'-'FamilyStorage'-'Record')'.-'-'-'

'-'-'-.('Record'-'Inventory'-'Transactions')'.-'-'-'
'-'-'-.('Record'-'Transactions'-'Inventory')'.-'-'-'
'-'-'-.('Transactions'-'Inventory'-'Record')'.-'-'-'
'-'-'-.('Transactions'-'Record'-'Inventory')'.-'-'-'
'-'-'-.('Inventory'-'Record'-'Transactions')'.-'-'-'
'-'-'-.('Inventory'-'Transactions'-'Record')'.-'-'-'

'-'-'-.('Inventory'-'TransactionRecords'-'Inventory')'.-'-'-'
'-'-'-.('TransactionRecords'-'Inventory'-'TransactionRecords')'.-'-'-'
'-'-'-.('FamilyInventory'-'TransactionRecords'-'FamilyInventory')'.-'-'-'
'-'-'-.('TransactionRecords'-'FamilyInventory'-'TransactionRecords')'.-'-'-'

'-'-'-.('Trade'-'FromInventory'-'Trade')'.-'-'-'
'-'-'-.('FromInventory'-'Trade'-'FromInventory')'.-'-'-'

'-'-'-.('ShareQuest'-'SageSkill'-'ShareQuest')'.-'-'-'
'-'-'-.('SageSkill'-'ShareQuest'-'SageSkill')'.-'-'-'
'-'-'-.('ShareQuestLog'-'SageSkill'-'ShareQuestLog')'.-'-'-'
'-'-'-.('SageSkill'-'ShareQuestLog'-'SageSkill')'.-'-'-'
'-'-'-.('ShareAvailableQuests'-'SageSkill'-'ShareAvailableQuests')'.-'-'-'
'-'-'-.('SageSkill'-'ShareAvailableQuests'-'SageSkill')'.-'-'-'
'-'-'-.('ShareQuestDetails'-'SageSkill'-'ShareQuestDetails')'.-'-'-'
'-'-'-.('SageSkill'-'ShareQuestDetails'-'SageSkill')'.-'-'-'

'-'-'-.('SageAura'-'SageSkill'-'ShieldArea')'.-'-'-'
'-'-'-.('ShieldArea'-'SageSkill'-'SageAura')'.-'-'-'

'-'-'-.('MagicRod'-'SageSkill'-'MagicRod')'.-'-'-'
'-'-'-.('SageSkill'-'MagicRod'-'SageSkill')'.-'-'-'

'-'-'-.('EnergyCoat'-'SageSkill'-'EnergyCoat')'.-'-'-'
'-'-'-.('SageSkill'-'EnergyCoat'-'SageSkill')'.-'-'-'

'-'-'-.('SoulSyphon'-'SageSkill'-'SoulSyphon')'.-'-'-'
'-'-'-.('SageSkill'-'SoulSyphon'-'SageSkill')'.-'-'-'

'-'-'-.('Indulge'-'SageSkill'-'Indulge')'.-'-'-'
'-'-'-.('SageSkill'-'Indulge'-'SageSkill')'.-'-'-'
'-'-'-.('SoulExhale'-'SageSkill'-'SoulExhale')'.-'-'-'
'-'-'-.('SageSkill'-'SoulExhale'-'SageSkill')'.-'-'-'

'-'-'-.('ClearCast'-'SageSkill'-'ClearCast')'.-'-'-'
'-'-'-.('SageSkill'-'ClearCast'-'SageSkill')'.-'-'-'

'-'-'-.('SpellBreaker'-'SageSkill'-'SpellBreaker')'.-'-'-'
'-'-'-.('SageSkill'-'SpellBreaker'-'SageSkill')'.-'-'-'


'-'-'-.('Indulge'-'SageSkill'-'Indulge')'.-'-'-'
'-'-'-.('SageSkill'-'Indulge'-'SageSkill')'.-'-'-'
'-'-'-.('SoulExhale'-'SageSkill'-'SoulExhale')'.-'-'-'
'-'-'-.('SageSkill'-'SoulExhale'-'SageSkill')'.-'-'-'

'-'-'-.('ClearCast'-'SageSkill'-'ClearCast')'.-'-'-'
'-'-'-.('SageSkill'-'ClearCast'-'SageSkill')'.-'-'-'

'-'-'-.('SpellBreaker'-'SageSkill'-'SpellBreaker')'.-'-'-'
'-'-'-.('SageSkill'-'SpellBreaker'-'SageSkill')'.-'-'-'

'-'-'-.('Craft'-'SageSkill'-'ElementalConverter')'.-'-'-'
'-'-'-.('ElementalConverter'-'SageSkill'-'Craft')'.-'-'-'

'-'-'-.('TargetWeapon'-'ElementalConverter'-'TargetWeapon')'.-'-'-'
'-'-'-.('ElementalConverter'-'TargetWeapon'-'ElementalConverter')'.-'-'-'

'-'-'-.('ElementChange'-'SageSkill'-'ElementChange')'.-'-'-'
'-'-'-.('SageSkill'-'ElementChange'-'SageSkill')'.-'-'-'

'-'-'-.('Hindsight'-'SageSkill'-'Hindsight')'.-'-'-'
'-'-'-.('SageSkill'-'Hindsight'-'SageSkill')'.-'-'-'

'-'-'-.('HeavensDrive'-'SageSkill'-'HeavensDrive')'.-'-'-'
'-'-'-.('SageSkill'-'HeavensDrive'-'HeavensDrive')'.-'-'-'

'-'-'-.('EarthSpike'-'SageSkill'-'EarthSpike')'.-'-'-'
'-'-'-.('SageSkill'-'EarthSpike'-'SageSkill')'.-'-'-'

'-'-'-.('Dragonology'-'SageSkill'-'Dragonology')'.-'-'-'
'-'-'-.('SageSkill'-'Dragonology'-'SageSkill')'.-'-'-'

'-'-'-.('Dispell'-'SageSkill'-'Dispell')'.-'-'-'
'-'-'-.('SageSkill'-'Dispell'-'SageSkill')'.-'-'-'

'-'-'-.('FreeCast'-'SageSkill'-'FreeCast')'.-'-'-'
'-'-'-.('SageSkill'-'FreeCast'-'SageSkill')'.-'-'-'

'-'-'-.('Deluge'-'SageSkill'-'Deluge')'.-'-'-'
'-'-'-.('SageSkill'-'Deluge'-'SageSkill')'.-'-'-'

'-'-'-.('EndowBlaze'-'SageSkill'-'EndowBlaze')'.-'-'-'
'-'-'-.('SageSkill'-'EndowBlaze'-'SageSkill')'.-'-'-'

'-'-'-.('EndowQuake'-'SageSkill'-'EndowQuake')'.-'-'-'
'-'-'-.('SageSkill'-'EndowQuake'-'SageSkill')'.-'-'-'

'-'-'-.('EndowTornado'-'SageSkill'-'EndowTornado')'.-'-'-'
'-'-'-.('SageSkill'-'EndowTornado'-'SageSkill')'.-'-'-'
'-'-'-.('EndowTsunami'-'SageSkill'-'EndowTsunami')'.-'-'-'
'-'-'-.('SageSkill'-'EndowTsunami'-'SageSkill')'.-'-'-'
'-'-'-.('Study'-'SageSkill'-'Study')'.-'-'-'
'-'-'-.('SageSkill'-'Study'-'SageSkill')'.-'-'-'
'-'-'-.('Volcano'-'SageSkill'-'Volcano')'.-'-'-'
'-'-'-.('SageSkill'-'Volcano'-'SageSkill')'.-'-'-'
'-'-'-.('Sense'-'SageSkill'-'Sense')'.-'-'-'
'-'-'-.('SageSkill'-'Sense'-'SageSkill')'.-'-'-'
'-'-'-.('SoulLink'-'SageSkill'-'SoulLink')'.-'-'-'
'-'-'-.('SageSkill'-'SoulLink'-'SageSkill')'.-'-'-'
'-'-'-.('FiberLock'-'SageSkill'-'FiberLock')'.-'-'-'
'-'-'-.('SageSkill'-'FiberLock'-'SageSkill')'.-'-'-'
'-'-'-.('Foresight'-'SageSkill'-'Foresight')'.-'-'-'
'-'-'-.('SageSkill'-'Foresight'-'SageSkill')'.-'-'-'
'-'-'-.('DoubleBolt'-'SageSkill'-'DoubleBolt')'.-'-'-'
'-'-'-.('SageSkill'-'DoubleBolt'-'SagSkill')'.-'-'-'
'-'-'-.('MindBreaker'-'SageSkill '-'MindBreaker')'.-'-'-'
'-'-'-.('SageSkill'-'MindBreaker'-'SageSkill')'.-'-'-'
'-'-'-.('BlindingMist'-'SageSkill'-'BlindingMist')'.-'-'-'
'-'-'-.('SageSkill'-'BlindingMist'-'SageSkill')'.-'-'-'
'-'-'-.('SafetyWall'-'SageSkill'-'SafetyWall')'.-'-'-'
'-'-'-.('SageSkill'-'SafetyWall'-'SageSkill')'.-'-'-'


'-'-'-.('SoulLinker'-'SageSkill'-'SoulLinker')'.-'-'-'
'-'-'-.('SageSkill'-'SoulLinker'-'SageSkill')'.-'-'-'

'-'-'-.('LinkSoul'-'SoulLinker'-'LinkSoul')'.-'-'-'
'-'-'-.('SoulLinker'-'LinkSoul'-'SoulLinker')'.-'-'-'

'-'-'-.('Eska'-'SoulLinker'-'Eska')'.-'-'-'
'-'-'-.('SoulLinker'-'Eska'-'SoulLinker')'.-'-'-'
'-'-'-.('Eske'-'SoulLinker'-'Eske')'.-'-'-'
'-'-'-.('SoulLinker'-'Eske'-'SoulLinker')'.-'-'-'
'-'-'-.('Esma'-'SoulLinker'-'Esma')'.-'-'-'
'-'-'-.('SoulLinker'-'Esma'-'SoulLinker')'.-'-'-'
'-'-'-.('Estin SoulLinker'-'Estin')'.-'-'-'
'-'-'-.('SoulLinker'-'Estin'-'SoulLinker')'.-'-'-'
'-'-'-.('Estun'-'SoulLinker'-'Estun')'.-'-'-'
'-'-'-.('SoulLinker'-'Estun'-'SoulLinker')'.-'-'-'
'-'-'-.('Eswoo'-'SoulLinker'-'Eswoo')'.-'-'-'
'-'-'-.('SoulLinker'-'Eswoo'-'SoulLinker')'.-'-'-'
'-'-'-.('Kaahi'-'SoulLinker'-'Kaahi')'.-'-'-'
'-'-'-.('SoulLinker'-'Kaahi'-'SoulLinker')'.-'-'-'
'-'-'-.('Kaina'-'SoulLinker'-'Kaina')'.-'-'-'
'-'-'-.('SoulLinker'-'Kaina'-'SoulLinker')'.-'-'-'
'-'-'-.('Kaite'-'SoulLinker'-'Kaite')'.-'-'-'
'-'-'-.('SoulLinker'-'Kaite'-'SoulLinker')'.-'-'-'
'-'-'-.('Kaizel'-'SoulLinker'-'Kaizel')'.-'-'-'
'-'-'-.('SoulLinker'-'Kaizel'-'SoulLinker')'.-'-'-'
'-'-'-.('Kaupe'-'SoulLinker'-'Kaupe')'.-'-'-'
'-'-'-.('SoulLinker'-'Kaupe'-'SoulLinker')'.-'-'-'
'-'-'-.('1stTransSpirit'-'SoulLinker'-'1stTransSpirit')'.-'-'-'
'-'-'-.('SoulLinker'-'1stTransSpirit'-'SoulLinker')'.-'-'-'
'-'-'-.(''('ClassSpirits')'.-'-'-''-'SoulLinker'-'-'-'-.('ClassSpirits')'.-'-'-'')'.-'-'-'
'-'-'-.('SoulLinker'-'ClassSpirits'-'SoulLinker')'.-'-'-'
'-'-'-.(''('ClassSpirits')'.-'-'-''-'SageSkill'-'-'-'-.('ClassSpirits')'.-'-'-'')'.-'-'-'
'-'-'-.('LinkerSkill'-'ClassSpirits'-'LinkerSkill')'.-'-'-'

'-'-'-.(''('Mistress Sunglasses')'.-'-'-' SageSkill'-'-'-'-.('Mistress Sunglasses')'.-'-'-'')'.-'-'-'
'-'-'-.('SageSkill 'Mistress Sunglasses' SageSkill')'.-'-'-'

'-'-'-.(''('Wizard Eyes')'.-'-'-' SageSkill'-'-'-'-.('Wizard Eyes')'.-'-'-'')'.-'-'-'
'-'-'-.('SageSkill 'Wizard Eyes' SageSkill')'.-'-'-'

'-'-'-.(''('Priest Eyes')'.-'-'-' SageSkill'-'-'-'-.('Priest Eyes')'.-'-'-'')'.-'-'-'
'-'-'-.('SageSkill 'Priest Eyes' SageSkill')'.-'-'-'

'-'-'-.(''('Sage Eyes')'.-'-'-' SageSkill'-'-'-'-.('Sage Sight')'.-'-'-'')'.-'-'-'
'-'-'-.('SageSkill 'Sage Sight' SageSkill')'.-'-'-'

'-'-'-.(''('Alchemist Eyes')'.-'-'-' SageSkill'-'-'-'-.('Alchemist Eyes')'.-'-'-'')'.-'-'-'
'-'-'-.('SageSkill 'Alchemist Eyes' SageSkill')'.-'-'-'

'-'-'-.(''('Knight Eyes')'.-'-'-' SageSkill'-'-'-'-.('Knight Eyes')'.-'-'-'')'.-'-'-'
'-'-'-.('SageSkill 'Knight Eyes' SageSkill')'.-'-'-'

'-'-'-.(''('Elf Eyes')'.-'-'-' SageSkill'-'-'-'-.('Elf Eyes')'.-'-'-'')'.-'-'-'
'-'-'-.('SageSkill 'Elf Eyes' SageSkill')'.-'-'-'

'-'-'-.(''('Demon Eyes')'.-'-'-' SageSkill'-'-'-'-.('Demon Eyes')'.-'-'-'')'.-'-'-'
'-'-'-.('SageSkill 'Demon Eyes' SageSkill')'.-'-'-'

'-'-'-.(''('Monkey Eyes')'.-'-'-' SageSkill'-'-'-'-.('Monkey Eyes')'.-'-'-'')'.-'-'-'
'-'-'-.('SageSkill 'Monkey Eyes' SageSkill')'.-'-'-'

'-'-'-.(''('Sharingan Eyes')'.-'-'-' SageSkill'-'-'-'-.('Sharingan Eyes')'.-'-'-'')'.-'-'-'
'-'-'-.('SageSkill 'Sharingan Eyes' SageSkill')'.-'-'-'

'-'-'-.(''('Byakugan Eyes')'.-'-'-' SageSkill'-'-'-'-.('Byakugan Eyes')'.-'-'-'')'.-'-'-'
'-'-'-.('SageSkill 'Byakugan Eyes' SageSkill')'.-'-'-'

'-'-'-.(''('Rinnegan Eyes')'.-'-'-' SageSkill'-'-'-'-.('Rinnegan Eyes')'.-'-'-'')'.-'-'-'
'-'-'-.('SageSkill 'Rinnegan Eyes' SageSkill')'.-'-'-'

'-'-'-.(''('Tenseigan Eyes')'.-'-'-' SageSkill'-'-'-'-.('Tenseigan Eyes')'.-'-'-'')'.-'-'-'
'-'-'-.('SageSkill 'Tenseigan Eyes' SageSkill')'.-'-'-'

'-'-'-.(''('Mangekyou Sharingan Eyes')'.-'-'-' SageSkill'-'-'-'-.('Mangekyou Sharingan Eyes')'.-'-'-'')'.-'-'-'
'-'-'-.('SageSkill 'Mangekyo Sharingan Eyes' SageSkill')'.-'-'-'

'-'-'-.(''('Jougan Eyes')'.-'-'-''-'SageSkill'-'-'-'-.('Jougan Eyes')'.-'-'-'')'.-'-'-'
'-'-'-.('SageSkill'-'Jougan Eyes'-'SageSkill')'.-'-'-'

'-'-'-.(''('Isshiki Eyes')'.-'-'-''-'SageSkill'-'-'-'-.('Isshiki Eyes')'.-'-'-'')'.-'-'-'
'-'-'-.('SageSkill'-'Isshiki Eyes'-'SageSkill')'.-'-'-'

'-'-'-.(''('Dragon Eyes')'.-'-'-''-'SageSkill'-'-'-'-.('Dragon Eyes')'.-'-'-'')'.-'-'-'
'-'-'-.('SageSkill'-'Dragon Eyes'-'SageSkill')'.-'-'-'



'-'-'-.('Magic'-'Aura'-'Control')'.-'-'-'
'-'-'-.('Control'-'Aura'-'Magic')'.-'-'-'
'-'-'-.('Magic'-'Control'-'Aura')'.-'-'-'
'-'-'-.('Aura'-'Magic'-'Control')'.-'-'-'

'-'-'-.('Flight'-'Aura'-'Manipluation')'.-'-'-'
'-'-'-.('Manipluation'-'Aura'-'Flight')'.-'-'-'
'-'-'-.('Aura'-'Manipulation'-'Flight')'.-'-'-'
'-'-'-.('Aura'-'Flight'-'Manipulation')'.-'-'-'

'-'-'-.('Flight'-'Magic'-'Manipluation')'.-'-'-'
'-'-'-.('Manipluation'-'Magic'-'Flight')'.-'-'-'
'-'-'-.('Magic'-'Manipulation'-'Flight')'.-'-'-'
'-'-'-.('Magic'-'Flight'-'Manipulation')'.-'-'-'

'-'-'-.('MP'-'Magic'-'MP')'.-'-'-'
'-'-'-.('Magic'-'MP'-'Magic')'.-'-'-'

'-'-'-.('HP'-'Magic'-'HP')'.-'-'-'
'-'-'-.('Magic'-'HP'-'Magic')'.-'-'-'

'-'-'-.('Shield'-'Magic'-'Shield')'.-'-'-'
'-'-'-.('Magic'-'Shield'-'Magic')'.-'-'-'

'-'-'-.('Armour'-'Magic'-'Armour')'.-'-'-'
'-'-'-.('Magic'-'Armour'-'Magic')'.-'-'-'

'-'-'-.('Inventory'-'Magic'-'Inventory')'.-'-'-'
'-'-'-.('Magic'-'Inventory'-'Magic')'.-'-'-'


'-'-'-.('EnvironmentLocation'-'ItemDrop'-'EnvironmentLocation')'.-'-'-'
'-'-'-.('ItemDrop'-'EnvironmentLocation'-'ItemDrop')'.-'-'-'
'-'-'-.('ItemNumber'-'EnvironmentLocation'-'ItemNumber')'.-'-'-'
'-'-'-.('ItemNumber'-'Magic'-'ItemName')'.-'-'-'
'-'-'-.('ItemName'-'Magic'-'ItemNumber')'.-'-'-'
'-'-'-.('EnvironmentLocation'-'ItemNumber'-'AddToInventory')'.-'-'-'
'-'-'-.('AddToInventory'-'ItemNumber'-'EnvironmentLocation')'.-'-'-'
'-'-'-.('ItemName'-'ItemNumber'-'ItemName')'.-'-'-'
'-'-'-.('ItemNumber'-'ItemName'-'ItemNumber')'.-'-'-'

'-'-'-.('Craft'-'Magic'-'Items')'.-'-'-'
'-'-'-.('Items'-'Magic'-'Craft')'.-'-'-'
'-'-'-.('Magic'-'Craft'-'Items')'.-'-'-'
'-'-'-.('Magic'-'Items'-'Craft')'.-'-'-'

'-'-'-.('Magic'-'Self'-'Improve')'.-'-'-'
'-'-'-.('Improve'-'Self'-'Magic')'.-'-'-'

'-'-'-.('Enchant'-'Magic'-'Items')'.-'-'-'
'-'-'-.('Items'-'Magic'-'Enchant')'.-'-'-'
'-'-'-.('Magic'-'Items'-'Enchant')'.-'-'-'
'-'-'-.('Enchant'-'Items'-'Magic')'.-'-'-'

'-'-'-.('Language'-'Movement'-'Self')'.-'-'-'
'-'-'-.('Self'-'Movement'-'Self')'.-'-'-'
'-'-'-.('Movement'-'Self'-'Movement')'.-'-'-'
'-'-'-.('Self'-'Movement'-'Language')'.-'-'-'

'-'-'-.('Flight'-'Self'-'Flight')'.-'-'-'
'-'-'-.('Self'-'Flight'-'Self')'.-'-'-'
'-'-'-.('Self'-'Flight'-'Flight')'.-'-'-'
'-'-'-.('Flight'-'Flight'-'Self')'.-'-'-'

'-'-'-.('Flight'-'Accelerate'-'Speed')'.-'-'-'
'-'-'-.('Speed'-'Accelerate'-'Flight')'.-'-'-'
'-'-'-.('Flight'-'Accellerate'-'Accellerate')'.-'-'-'
'-'-'-.('Accellerate'-'Accellerate'-'Flight')'.-'-'-'

'-'-'-.('Language'-'Memory'-'Language')'.-'-'-'
'-'-'-.('Memory'-'Language'-'Memory')'.-'-'-'

'-'-'-.('Language'-'Human'-'Language')'.-'-'-'
'-'-'-.('Human'-'Language'-'Human')'.-'-'-'
'-'-'-.('Language'-'Baby'-'Language')'.-'-'-'
'-'-'-.('Baby'-'Language'-'Baby')'.-'-'-'
'-'-'-.('Male'-'Language'-'Male')'.-'-'-'
'-'-'-.('Language'-'Male'-'Language')'.-'-'-'
'-'-'-.('Female'-'Language'-'Female')'.-'-'-'
'-'-'-.('Language'-'Female'-'Language')'.-'-'-'
'-'-'-.('Male'-'Language'-'Male')'.-'-'-'
'-'-'-.('Language'-'Male'-'Language')'.-'-'-'

'-'-'-.('Language'-'Demon'-'Language')'.-'-'-'
'-'-'-.('Demon'-'Language'-'Demon')'.-'-'-'
'-'-'-.('Language'-'Elf'-'Language')'.-'-'-'
'-'-'-.('Elf'-'Language'-'Elf')'.-'-'-'
'-'-'-.('Language'-'Dwarf'-'Language')'.-'-'-'
'-'-'-.('Dwarf'-'Language'-'Dwarf')'.-'-'-'

'-'-'-.('Language'-'Monsters'-'Language')'.-'-'-'
'-'-'-.('Monsters'-'Language'-'Monsters')'.-'-'-'
'-'-'-.('Language'-'Animals'-'Language')'.-'-'-'
'-'-'-.('Animals'-'Language'-'Animals')'.-'-'-'

'-'-'-.('Language'-'Time'-'Language')'.-'-'-'
'-'-'-.('Time'-'Language'-'Time')'.-'-'-'
'-'-'-.('Language'-'Space'-'Language')'.-'-'-'
'-'-'-.('Space'-'Language'-'Space')'.-'-'-'
'-'-'-.('Language'-'Multivere'-'Language')'.-'-'-'
'-'-'-.('Multiverse'-'Language'-'Multiverse')'.-'-'-'

'-'-'-.('Language'-'Flight'-'Language')'.-'-'-'
'-'-'-.('Flight'-'Language'-'Flight')'.-'-'-'

'-'-'-.('Language'-'Gravity'-'Language')'.-'-'-'
'-'-'-.('Gravity'-'Language'-'Gravity')'.-'-'-'

'-'-'-.('Language'-'Everything'-'Language')'.-'-'-'
'-'-'-.('Everything'-'Language'-'Everything')'.-'-'-'
'-'-'-.('Language'-'Nothing'-'Language')'.-'-'-'
'-'-'-.('Nothing'-'Language'-'Nothing')'.-'-'-'

'-'-'-.('Self'-'Language'-'Programming')'.-'-'-'
'-'-'-.('Programming'-'New'-'Programming')'.-'-'-'
'-'-'-.('New'-'Programming'-'New')'.-'-'-'

'-'-'-.('Language'-'Enemy'-'Language')'.-'-'-'
'-'-'-.('Enemy'-'Language'-'Language')'.-'-'-'
'-'-'-.('Language'-'Self'-'Language')'.-'-'-'
'-'-'-.('Self'-'Language'-'Self')'.-'-'-'
'-'-'-.('Language'-'Love'-'Language')'.-'-'-'
'-'-'-.('Love'-'Language'-'Language')'.-'-'-'
'-'-'-.('Language'-'War'-'Language')'.-'-'-'
'-'-'-.('War'-'Language'-'Language')'.-'-'-'
'-'-'-.('Language'-'Battle'-'Language')'.-'-'-'
'-'-'-.('Battle'-'Language'-'Language')'.-'-'-'
'-'-'-.('Hunger'-'Battle'-'Hunger')'.-'-'-'
'-'-'-.('Battle'-'Hunger'-'Language')'.-'-'-'
'-'-'-.('Sight'-'Human'-'Sight')'.-'-'-'
'-'-'-.('Human'-'Sight'-'Human')'.-'-'-'
'-'-'-.('Sound'-'Human'-'Sound')'.-'-'-'
'-'-'-.('Human'-'Sound'-'Human'
'-'-'-.('Voice'-'Human'-'Voice')'.-'-'-'
'-'-'-.('Human'-'Voice'-'Human')'.-'-'-'
'-'-'-.('Speech'-'Human'-'Speech')'.-'-'-'
'-'-'-.('Human'-'Speech'-'Human')'.-'-'-'
'-'-'-.('Gender'-'Human'-'Gender')'.-'-'-'
'-'-'-.('Human'-'Gender'-'Human')'.-'-'-'

'-'-'-.('Interface'-'Developer'-'Interface')'.-'-'-'
'-'-'-.('Developer'-'Interface'-'Developer')'.-'-'-'
'-'-'-.('Interface'-'Player'-'Interface')'.-'-'-'
'-'-'-.('Player'-'Interface'-'Player')'.-'-'-'
'-'-'-.('Interface'-'System'-'Interface')'.-'-'-'
'-'-'-.('System'-'Interface'-'System')'.-'-'-'
'-'-'-.('Interface'-'User'-'Interface')'.-'-'-'
'-'-'-.('User'-'Interface'-'User')'.-'-'-'
'-'-'-.('Interface'-'Self'-'Interface')'.-'-'-'
'-'-'-.('Self'-'Interface'-'Self')'.-'-'-'

'-'-'-.('Magic'-'Wizard'-'Magic')'.-'-'-'
'-'-'-.('Wizard'-'Magic'-'Wizard')'.-'-'-'
'-'-'-.('Sight'-'Wizard'-'Sight')'.-'-'-'
'-'-'-.('Wizard'-'Sight'-'Wizard')'.-'-'-'
'-'-'-.('Language'-'Wizard'-'Language')'.-'-'-'
'-'-'-.('Wizard'-'Language'-'Wizard')'.-'-'-'
'-'-'-.('Sound'-'Wizard'-'Sound')'.-'-'-'
'-'-'-.('Wizard'-'Sound'-'Wizard')'.-'-'-'
'-'-'-.('Voice'-'Wizard'-'Smell')'.-'-'-'
'-'-'-.('Wizard'-'Smell'-'Wizard')'.-'-'-'
'-'-'-.('Wizard'-'Color'-'Wizard')'.-'-'-'
'-'-'-.('Wizard'-'Gender'-'Wizard')'.-'-'-'
'-'-'-.('Gender'-'Wizard'-'Gender')'.-'-'-'
'-'-'-.('Taste'-'Wizard'-'Taste')'.-'-'-'
'-'-'-.('Wizard'-'Taste'-'Wizard')'.-'-'-'

'-'-'-.('Magic'-'Sage'-'Magic')'.-'-'-'
'-'-'-.('Sage'-'Magic'-'Sage')'.-'-'-'
'-'-'-.('Color'-'Sage'-'Color')'.-'-'-'
'-'-'-.('Sage'-'Color'-'Sage')'.-'-'-'
'-'-'-.('Smell'-'Sage'-'Smell')'.-'-'-'
'-'-'-.('Sage'-'Smell'-'Sage')'.-'-'-'
'-'-'-.('Taste'-'Sage'-'Taste')'.-'-'-'
'-'-'-.('Sage'-'Taste'-'Sage')'.-'-'-'
'-'-'-.('Gender'-'Sage'-'Gender')'.-'-'-'
'-'-'-.('Sage'-'Gender'-'Sage')'.-'-'-'

'-'-'-.('FireBolt'-'Skills'-'FireBolt')'.-'-'-'
'-'-'-.('LightningBolt'-'Skills'-'LightingBolt')'.-'-'-'

'-'-'-.('Male'-'Elf'-'Male')'.-'-'-'
'-'-'-.('Elf'-'Male'-'Elf')'.-'-'-'
'-'-'-.('Female'-'Elf'-'Female')'.-'-'-'
'-'-'-.('Elf'-'Female'-'Elf')'.-'-'-'
'-'-'-.('Taste'-'Elf'-'Taste')'.-'-'-'
'-'-'-.('Elf'-'Taste'-'Elf')'.-'-'-'

'-'-'-.('Change'-'Self'-'Change')'.-'-'-'
'-'-'-.('Self'-'Change'-'Self')'.-'-'-'

'-'-'-.('Target'-'Change'-'Target')'.-'-'-'
'-'-'-.('Change'-'Target'-'Change')'.-'-'-'

'-'-'-.('Touch'-'Self'-'Touch')'.-'-'-'
'-'-'-.('Self'-'Touch'-'Self')'.-'-'-'

'-'-'-.('Taste'-'DemonKing'-'Taste')'.-'-'-'
'-'-'-.('DemonKing'-'Taste'-'DemonKing')'.-'-'-'

'-'-'-.('Mirror'-'Magic'-'Mirror')'.-'-'-'
'-'-'-.('Magic'-'Mirror'-'Magic')'.-'-'-'
